package Mensaje;

public enum KindMensaje {
    MENSAJE_CONEXION, MENSAJE_CONFIRMACION_CONEXION, MENSAJE_SOLICITUD_INFO, MENSAJE_CONFIRMACION_SOLICITUD_INFO,
    MENSAJE_SOLICITUD_LIBRO, MENSAJE_DAR_LIBRO, MENSAJE_COMPARTIR_LIBRO, MENSAJE_PREPARADO_CS, MENSAJE_PREPARADO_SC,
    MENSAJE_CERRAR_CONEXION, MENSAJE_CONFIRMACION_CERRADO, MENSAJE_ERROR, MENSAJE_NUEVO_PROPIETARIO, MENSAJE_CERRAR_P2P,
    MENSAJE_CONFIRMACION_CERRADO_P2P, MENSAJE_LIBRO_LISTO
}
